name: apna_ai
description: A starter Flutter app like Perplexity AI
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  mistralai_dart: ^0.0.6
  flutter_markdown: ^0.6.18
  web_socket_channel: ^2.3.0
  image_picker: ^0.8.7+5
  supabase_flutter: ^1.4.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  audioplayers: ^6.0.0
  record: ^6.1.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  metadata_fetch: ^0.4.2
  sqflite: ^2.4.2
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^12.0.2
  upi_india: ^3.0.1       # Google Pay, PhonePe, etc.
  http: ^1.5.0            # For PayPal API
  lottie: ^3.3.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/payment_success.json
    - assets/animations/payment_failed.json
